version: '3.8'

services:
    redis:
      image: redis
    db:
      image: postgres
      restart: always
      environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: postgres
    backend:
      build: ./example-backend
      ports:
        - 8080:8080
      environment:
        REQUEST_ORIGIN: http://localhost:5000
        REDIS_HOST: redis
        POSTGRES_HOST: db
      depends_on:
        - redis
    frontend:
      build: ./example-frontend
      ports:
        - 5000:5000
      depends_on:
        - backend